lolol_shop_homepage:
    pattern:  /
    defaults: { _controller: LololShopBundle:Shop:index }

lolol_shop_champions:
    pattern:  /champions
    defaults: { _controller: LololShopBundle:Shop:champions }

lolol_shop_items:
    pattern:  /items
    defaults: { _controller: LololShopBundle:Shop:items }
    
lolol_shop_buyChampion:
    pattern: /buy/champion/{id}
    defaults: { _controller: LololShopBundle:Shop:buyChampion }
    
lolol_shop_buyItem:
    pattern: /buy/item/{id}
    defaults: { _controller: LololShopBundle:Shop:buyItem }