lolol_shop_homepage:
    pattern:  /shop/
    defaults: { _controller: LololShopBundle:Shop:index }

lolol_shop_champions:
    pattern:  /shop/champions
    defaults: { _controller: LololShopBundle:Shop:champions }

lolol_shop_items:
    pattern:  /shop/items
    defaults: { _controller: LololShopBundle:Shop:items }
    
lolol_shop_buyChampion:
    pattern: /shop/buy/champion/{id}
    defaults: { _controller: LololShopBundle:Shop:buyChampion }
    
lolol_shop_buyItem:
    pattern: /shop/buy/item/{id}
    defaults: { _controller: LololShopBundle:Shop:buyItem }