parameters:
#    lolol_battle.example.class: Lolol\BattleBundle\Example

services:
    lolol_battle.battleManager:
        class: Lolol\BattleBundle\BattleManager\BattleManager
        arguments: [@lolol_battle.logger, @lolol_battle.logTypesManager, @translator, @logger]
        
    lolol_battle.logger:
        class: Lolol\BattleBundle\BattleManager\BattleLogger
#        arguments: [@service_id, "plain_value", %parameter%]

    lolol_battle.logTypesManager:
        class: Lolol\BattleBundle\BattleManager\LogTypesManager
        arguments: [@doctrine.orm.entity_manager]

#    lolol_battle.example:
#        class: %lolol_battle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
