lolol_shop:
    resource: "@LololShopBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

lolol_app:
    resource: "@LololAppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

lolol_user:
    resource: "@LololUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

lolol_team:
    resource: "@LololTeamBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en