parameters:
#    lolol_user.example.class: Lolol\UserBundle\Example

services:
#    lolol_user.example:
#        class: %lolol_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
