parameters:
#    lolol_battle.example.class: Lolol\BattleBundle\Example

services:
#    lolol_battle.example:
#        class: %lolol_battle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
