lolol_battle:
    resource: "@LololBattleBundle/Resources/config/routing.yml"
    prefix:   /

lolol_super_admin:
    resource: "@LololSuperAdminBundle/Resources/config/routing.yml"
    prefix:   /

lolol_shop:
    resource: "@LololShopBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/shop
    requirements:
        _locale: fr|en

lolol_app:
    resource: "@LololAppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

lolol_user:
    resource: "@LololUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

lolol_team:
    resource: "@LololTeamBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/team
    requirements:
        _locale: fr|en
        
lolol_battle:
    resource: "@LololBattleBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/battle
    requirements:
        _locale: fr|en