lolol_super_admin_homepage:
    pattern:  /
    defaults: { _controller: LololSuperAdminBundle:SuperAdmin:index }
    
lolol_super_admin_retrieveChampions:
    pattern:  /retrieve
    defaults: { _controller: LololSuperAdminBundle:SuperAdmin:retrieveChampions }

lolol_super_admin_retrieveProcess:
    pattern:  /retrieveProcess
    defaults: { _controller: LololSuperAdminBundle:SuperAdmin:retrieveProcess }

lolol_super_admin_populateChampions:
    pattern:  /populateChampions
    defaults: { _controller: LololSuperAdminBundle:SuperAdmin:populateChampions }