lolol_team_myteams:
    pattern:  /myteams/
    defaults: { _controller: LololTeamBundle:Team:myTeams }
lolol_team_newteam:
    pattern:  /newteam/
    defaults: { _controller: LololTeamBundle:Team:newTeam }