lolol_team_myteams:
    pattern:  /my-teams/
    defaults: { _controller: LololTeamBundle:Team:myTeams }
lolol_team_newteam:
    pattern:  /team-builder/
    defaults: { _controller: LololTeamBundle:Team:teamBuilder }
lolol_team_newteamSave:
    pattern:  /team-builder/save
    defaults: { _controller: LololTeamBundle:Team:teamSave } 