lolol_team_myTeams:
    pattern:  /list/
    defaults: { _controller: LololTeamBundle:Team:list }
lolol_team_teamBuilder:
    pattern:  /builder/{id}
    defaults: { _controller: LololTeamBundle:Team:builder, id: 0 }
    requirements:
        id: \d+
lolol_team_teamSave:
    pattern:  /save
    defaults: { _controller: LololTeamBundle:Team:save }
lolol_team_teamDelete:
    pattern:  /delete/{id}
    defaults: { _controller: LololTeamBundle:Team:delete, id: 0 }
    requirements:
        id: \d+
lolol_team_consult:
    pattern:  /consult/{id}
    defaults: { _controller: LololTeamBundle:Team:consult, id: 0 }
    requirements:
        id: \d+