<?php

namespace Lolol\BattleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lolol\TeamBundle\Entity\Team;

/**
 * BattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleRepository extends EntityRepository {

}
