<?php

namespace Lolol\BattleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository {
	public function insertLogs($logs, $id) {
		$query = $this->_em->createNativeQuery('INSERT INTO Log() ', $rsm);
		
		$users = $query->getResult();
	}
	
}
