<?php

namespace Lolol\BattleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogTypeRepository extends EntityRepository {
	
	/**
	 * Get the log types as associative array.
	 * 
	 * @return array
	 */
	public function getLogTypesAsArray() {
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('lt')->from('LololBattleBundle:LogType', 'lt');
		
		$result = array();
		foreach($qb->getQuery()->getResult() as $logType) {
			$result[$logType->getKey()] = $logType;
		}
		
		return $result;
	}
}
