lolol_team_myTeams:
    pattern:  /my-teams/
    defaults: { _controller: LololTeamBundle:Team:myTeams }
lolol_team_teamBuilder:
    pattern:  /team-builder/{id}
    defaults: { _controller: LololTeamBundle:Team:teamBuilder, id: 1 }
    requirements:
        id: \d+
lolol_team_teamBuilderSave:
    pattern:  /team-builder/save
    defaults: { _controller: LololTeamBundle:Team:teamBuilderSave } 