parameters:
#    lolol_team.example.class: Lolol\TeamBundle\Example

services:
    lolol_team.champions:
        class: Lolol\TeamBundle\Champions\LololChampions
    lolol_app.paramconverter_test:
        class: Lolol\TeamBundle\ParamConverter\TeamParamConverter
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: request.param_converter, priority: 20 }
    lolol_team.teamManager:
        class: Lolol\TeamBundle\TeamManager\TeamManager
        arguments: [@lolol_battle.logger, @lolol_app.championManager]
#    lolol_team.example:
#        class: %lolol_team.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
