parameters:
#    lolol_team.example.class: Lolol\TeamBundle\Example

services:
    lolol_team.champions:
        class: Lolol\TeamBundle\Champions\LololChampions
#    lolol_team.example:
#        class: %lolol_team.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
