<?php

namespace Lolol\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lolol\TeamBundle\Entity\Team;

/**
 * ChampionTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionTeamRepository extends EntityRepository {
	public function getWithChampionsByTeam(Team $team, $orderBy = 'ct.position') {		
		return $this->findTeamWithChampionsById($team->getId(), $orderBy);
	}
	
	public function findTeamWithChampionsById($id, $orderBy = 'ct.position') {
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('ct')
		->from('LololTeamBundle:ChampionTeam', 'ct')
		->leftJoin('ct.champion', 'c')
		->addSelect('c')
		->where('ct.team = :teamId')
		->setParameter('teamId', $id)
		->orderBy($orderBy, 'ASC');
		
		return $qb->getQuery()
		->getResult();
	}
}
