<?php

namespace Lolol\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lolol\TeamBundle\Entity\Team;

/**
 * ChampionTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionTeamRepository extends EntityRepository {
	public function getTeamsWithChampionsByUser(User $user) {
		$qb = $this->_em->createQueryBuilder();
	
		$qb->select('ct')
			->from('LololTeamBundle:ChampionTeam', 'ct')
			->leftJoin('ct.team', 't')
			->addSelect('t')
			->leftJoin('ct.champion', 'c')
			->addSelect('c')
			->where('t.user = :userId')
			->setParameter('userId', $user->getId());
	
		return $qb->getQuery()
				->getResult();
	}
	
	public function getWithChampionsByTeam(Team $team, $orderBy = 'ct.id') {
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('ct')
			->from('LololTeamBundle:ChampionTeam', 'ct')
			->leftJoin('ct.champion', 'c')
			->addSelect('c')
			->where('ct.team = :teamId')
			->setParameter('teamId', $team->getId())
			->orderBy($orderBy, 'ASC');
		
		return $qb->getQuery()
		->getResult();
	}
}
