parameters:
#    lolol_overview.example.class: Lolol\OverviewBundle\Example

services:
#    lolol_overview.example:
#        class: %lolol_overview.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
