parameters:
#    lolol_app.example.class: Lolol\AppBundle\Example

services:
#    lolol_app.example:
#        class: %lolol_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
